//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryExchangeClient.SecuredWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecuredWebService.SecuredWebServiceSoap")]
    public interface SecuredWebServiceSoap {
        
        // CODEGEN: Generating message contract since message AuthenticateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibraryExchangeClient.SecuredWebService.AuthenticateUserResponse AuthenticateUser(LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryExchangeClient.SecuredWebService.AuthenticateUserResponse> AuthenticateUserAsync(LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since message HelloWorldRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibraryExchangeClient.SecuredWebService.HelloWorldResponse HelloWorld(LibraryExchangeClient.SecuredWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryExchangeClient.SecuredWebService.HelloWorldResponse> HelloWorldAsync(LibraryExchangeClient.SecuredWebService.HelloWorldRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecuredWebServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string authenticatedTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthenticatedToken {
            get {
                return this.authenticatedTokenField;
            }
            set {
                this.authenticatedTokenField = value;
                this.RaisePropertyChanged("AuthenticatedToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecuredWebServiceSoapChannel : LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuredWebServiceSoapClient : System.ServiceModel.ClientBase<LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap>, LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap {
        
        public SecuredWebServiceSoapClient() {
        }
        
        public SecuredWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuredWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuredWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuredWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryExchangeClient.SecuredWebService.AuthenticateUserResponse LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap.AuthenticateUser(LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader) {
            LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest inValue = new LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            LibraryExchangeClient.SecuredWebService.AuthenticateUserResponse retVal = ((LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryExchangeClient.SecuredWebService.AuthenticateUserResponse> LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap.AuthenticateUserAsync(LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryExchangeClient.SecuredWebService.AuthenticateUserResponse> AuthenticateUserAsync(LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader) {
            LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest inValue = new LibraryExchangeClient.SecuredWebService.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryExchangeClient.SecuredWebService.HelloWorldResponse LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap.HelloWorld(LibraryExchangeClient.SecuredWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader) {
            LibraryExchangeClient.SecuredWebService.HelloWorldRequest inValue = new LibraryExchangeClient.SecuredWebService.HelloWorldRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            LibraryExchangeClient.SecuredWebService.HelloWorldResponse retVal = ((LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryExchangeClient.SecuredWebService.HelloWorldResponse> LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap.HelloWorldAsync(LibraryExchangeClient.SecuredWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryExchangeClient.SecuredWebService.HelloWorldResponse> HelloWorldAsync(LibraryExchangeClient.SecuredWebService.SecuredWebServiceHeader SecuredWebServiceHeader) {
            LibraryExchangeClient.SecuredWebService.HelloWorldRequest inValue = new LibraryExchangeClient.SecuredWebService.HelloWorldRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((LibraryExchangeClient.SecuredWebService.SecuredWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
