//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace LibraryExchangeClient.BookManagement {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBookManagement", Namespace="http://tempuri.org/")]
    public partial class BookManagement : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllAuthorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllGenresOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBookOfInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBookOfInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksOfInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksOfInterestByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksByYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksByTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksByAuthorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksByGenreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllBooksByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveBookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BookManagement() {
            this.Url = global::LibraryExchangeClient.Properties.Settings.Default.LibraryExchangeClient_BookManagement_BookManagement;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddAuthorCompletedEventHandler AddAuthorCompleted;
        
        /// <remarks/>
        public event GetAllAuthorsCompletedEventHandler GetAllAuthorsCompleted;
        
        /// <remarks/>
        public event GetAllTypesCompletedEventHandler GetAllTypesCompleted;
        
        /// <remarks/>
        public event GetAllGenresCompletedEventHandler GetAllGenresCompleted;
        
        /// <remarks/>
        public event AddBookCompletedEventHandler AddBookCompleted;
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event EditBookCompletedEventHandler EditBookCompleted;
        
        /// <remarks/>
        public event AddBookOfInterestCompletedEventHandler AddBookOfInterestCompleted;
        
        /// <remarks/>
        public event CheckBookOfInterestCompletedEventHandler CheckBookOfInterestCompleted;
        
        /// <remarks/>
        public event GetAllBooksOfInterestCompletedEventHandler GetAllBooksOfInterestCompleted;
        
        /// <remarks/>
        public event GetAllBooksOfInterestByUserCompletedEventHandler GetAllBooksOfInterestByUserCompleted;
        
        /// <remarks/>
        public event GetAllBooksCompletedEventHandler GetAllBooksCompleted;
        
        /// <remarks/>
        public event GetAllBooksByYearCompletedEventHandler GetAllBooksByYearCompleted;
        
        /// <remarks/>
        public event GetAllBooksByTitleCompletedEventHandler GetAllBooksByTitleCompleted;
        
        /// <remarks/>
        public event GetAllBooksByUserCompletedEventHandler GetAllBooksByUserCompleted;
        
        /// <remarks/>
        public event GetAllBooksByAuthorCompletedEventHandler GetAllBooksByAuthorCompleted;
        
        /// <remarks/>
        public event GetAllBooksByGenreCompletedEventHandler GetAllBooksByGenreCompleted;
        
        /// <remarks/>
        public event GetAllBooksByTypeCompletedEventHandler GetAllBooksByTypeCompleted;
        
        /// <remarks/>
        public event ReserveBookCompletedEventHandler ReserveBookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/AddAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResult AddAuthor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Author author, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("AddAuthor", new object[] {
                        author,
                        userName,
                        guid});
            return ((OperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddAuthorAsync(Author author, string userName, string guid) {
            this.AddAuthorAsync(author, userName, guid, null);
        }
        
        /// <remarks/>
        public void AddAuthorAsync(Author author, string userName, string guid, object userState) {
            if ((this.AddAuthorOperationCompleted == null)) {
                this.AddAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAuthorOperationCompleted);
            }
            this.InvokeAsync("AddAuthor", new object[] {
                        author,
                        userName,
                        guid}, this.AddAuthorOperationCompleted, userState);
        }
        
        private void OnAddAuthorOperationCompleted(object arg) {
            if ((this.AddAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAuthorCompleted(this, new AddAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllAuthors", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfAuthorUcBWdBTS GetAllAuthors([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllAuthors", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfAuthorUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAuthorsAsync(string userName, string guid) {
            this.GetAllAuthorsAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllAuthorsAsync(string userName, string guid, object userState) {
            if ((this.GetAllAuthorsOperationCompleted == null)) {
                this.GetAllAuthorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllAuthorsOperationCompleted);
            }
            this.InvokeAsync("GetAllAuthors", new object[] {
                        userName,
                        guid}, this.GetAllAuthorsOperationCompleted, userState);
        }
        
        private void OnGetAllAuthorsOperationCompleted(object arg) {
            if ((this.GetAllAuthorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllAuthorsCompleted(this, new GetAllAuthorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfstring GetAllTypes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllTypes", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfstring)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTypesAsync(string userName, string guid) {
            this.GetAllTypesAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllTypesAsync(string userName, string guid, object userState) {
            if ((this.GetAllTypesOperationCompleted == null)) {
                this.GetAllTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTypesOperationCompleted);
            }
            this.InvokeAsync("GetAllTypes", new object[] {
                        userName,
                        guid}, this.GetAllTypesOperationCompleted, userState);
        }
        
        private void OnGetAllTypesOperationCompleted(object arg) {
            if ((this.GetAllTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTypesCompleted(this, new GetAllTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllGenres", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfstring GetAllGenres([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllGenres", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfstring)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllGenresAsync(string userName, string guid) {
            this.GetAllGenresAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllGenresAsync(string userName, string guid, object userState) {
            if ((this.GetAllGenresOperationCompleted == null)) {
                this.GetAllGenresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllGenresOperationCompleted);
            }
            this.InvokeAsync("GetAllGenres", new object[] {
                        userName,
                        guid}, this.GetAllGenresOperationCompleted, userState);
        }
        
        private void OnGetAllGenresOperationCompleted(object arg) {
            if ((this.GetAllGenresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllGenresCompleted(this, new GetAllGenresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/AddBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResult AddBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Book book, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("AddBook", new object[] {
                        book,
                        userName,
                        guid});
            return ((OperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddBookAsync(Book book, string userName, string guid) {
            this.AddBookAsync(book, userName, guid, null);
        }
        
        /// <remarks/>
        public void AddBookAsync(Book book, string userName, string guid, object userState) {
            if ((this.AddBookOperationCompleted == null)) {
                this.AddBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBookOperationCompleted);
            }
            this.InvokeAsync("AddBook", new object[] {
                        book,
                        userName,
                        guid}, this.AddBookOperationCompleted, userState);
        }
        
        private void OnAddBookOperationCompleted(object arg) {
            if ((this.AddBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBookCompleted(this, new AddBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/AddUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultValueOfstring AddUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] User user) {
            object[] results = this.Invoke("AddUser", new object[] {
                        user});
            return ((OperationResultValueOfstring)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(User user) {
            this.AddUserAsync(user, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(User user, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        user}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/EditBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResult EditBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Book book, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("EditBook", new object[] {
                        book,
                        userName,
                        guid});
            return ((OperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void EditBookAsync(Book book, string userName, string guid) {
            this.EditBookAsync(book, userName, guid, null);
        }
        
        /// <remarks/>
        public void EditBookAsync(Book book, string userName, string guid, object userState) {
            if ((this.EditBookOperationCompleted == null)) {
                this.EditBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditBookOperationCompleted);
            }
            this.InvokeAsync("EditBook", new object[] {
                        book,
                        userName,
                        guid}, this.EditBookOperationCompleted, userState);
        }
        
        private void OnEditBookOperationCompleted(object arg) {
            if ((this.EditBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditBookCompleted(this, new EditBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/AddBookOfInterest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResult AddBookOfInterest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BookOfInterest book, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("AddBookOfInterest", new object[] {
                        book,
                        userName,
                        guid});
            return ((OperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddBookOfInterestAsync(BookOfInterest book, string userName, string guid) {
            this.AddBookOfInterestAsync(book, userName, guid, null);
        }
        
        /// <remarks/>
        public void AddBookOfInterestAsync(BookOfInterest book, string userName, string guid, object userState) {
            if ((this.AddBookOfInterestOperationCompleted == null)) {
                this.AddBookOfInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBookOfInterestOperationCompleted);
            }
            this.InvokeAsync("AddBookOfInterest", new object[] {
                        book,
                        userName,
                        guid}, this.AddBookOfInterestOperationCompleted, userState);
        }
        
        private void OnAddBookOfInterestOperationCompleted(object arg) {
            if ((this.AddBookOfInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBookOfInterestCompleted(this, new AddBookOfInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/CheckBookOfInterest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS CheckBookOfInterest(int bookid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool bookidSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("CheckBookOfInterest", new object[] {
                        bookid,
                        bookidSpecified,
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBookOfInterestAsync(int bookid, bool bookidSpecified, string userName, string guid) {
            this.CheckBookOfInterestAsync(bookid, bookidSpecified, userName, guid, null);
        }
        
        /// <remarks/>
        public void CheckBookOfInterestAsync(int bookid, bool bookidSpecified, string userName, string guid, object userState) {
            if ((this.CheckBookOfInterestOperationCompleted == null)) {
                this.CheckBookOfInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBookOfInterestOperationCompleted);
            }
            this.InvokeAsync("CheckBookOfInterest", new object[] {
                        bookid,
                        bookidSpecified,
                        userName,
                        guid}, this.CheckBookOfInterestOperationCompleted, userState);
        }
        
        private void OnCheckBookOfInterestOperationCompleted(object arg) {
            if ((this.CheckBookOfInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBookOfInterestCompleted(this, new CheckBookOfInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksOfInterest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookOfInterest6WXd3OUP GetAllBooksOfInterest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksOfInterest", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfBookOfInterest6WXd3OUP)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksOfInterestAsync(string userName, string guid) {
            this.GetAllBooksOfInterestAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksOfInterestAsync(string userName, string guid, object userState) {
            if ((this.GetAllBooksOfInterestOperationCompleted == null)) {
                this.GetAllBooksOfInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksOfInterestOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksOfInterest", new object[] {
                        userName,
                        guid}, this.GetAllBooksOfInterestOperationCompleted, userState);
        }
        
        private void OnGetAllBooksOfInterestOperationCompleted(object arg) {
            if ((this.GetAllBooksOfInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksOfInterestCompleted(this, new GetAllBooksOfInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksOfInterestByUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookOfInterest6WXd3OUP GetAllBooksOfInterestByUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksOfInterestByUser", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfBookOfInterest6WXd3OUP)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksOfInterestByUserAsync(string userName, string guid) {
            this.GetAllBooksOfInterestByUserAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksOfInterestByUserAsync(string userName, string guid, object userState) {
            if ((this.GetAllBooksOfInterestByUserOperationCompleted == null)) {
                this.GetAllBooksOfInterestByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksOfInterestByUserOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksOfInterestByUser", new object[] {
                        userName,
                        guid}, this.GetAllBooksOfInterestByUserOperationCompleted, userState);
        }
        
        private void OnGetAllBooksOfInterestByUserOperationCompleted(object arg) {
            if ((this.GetAllBooksOfInterestByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksOfInterestByUserCompleted(this, new GetAllBooksOfInterestByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooks([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooks", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksAsync(string userName, string guid) {
            this.GetAllBooksAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksAsync(string userName, string guid, object userState) {
            if ((this.GetAllBooksOperationCompleted == null)) {
                this.GetAllBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksOperationCompleted);
            }
            this.InvokeAsync("GetAllBooks", new object[] {
                        userName,
                        guid}, this.GetAllBooksOperationCompleted, userState);
        }
        
        private void OnGetAllBooksOperationCompleted(object arg) {
            if ((this.GetAllBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksCompleted(this, new GetAllBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksByYear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooksByYear(int year, [System.Xml.Serialization.XmlIgnoreAttribute()] bool yearSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksByYear", new object[] {
                        year,
                        yearSpecified,
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksByYearAsync(int year, bool yearSpecified, string userName, string guid) {
            this.GetAllBooksByYearAsync(year, yearSpecified, userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksByYearAsync(int year, bool yearSpecified, string userName, string guid, object userState) {
            if ((this.GetAllBooksByYearOperationCompleted == null)) {
                this.GetAllBooksByYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksByYearOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksByYear", new object[] {
                        year,
                        yearSpecified,
                        userName,
                        guid}, this.GetAllBooksByYearOperationCompleted, userState);
        }
        
        private void OnGetAllBooksByYearOperationCompleted(object arg) {
            if ((this.GetAllBooksByYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksByYearCompleted(this, new GetAllBooksByYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksByTitle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooksByTitle([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string title, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksByTitle", new object[] {
                        title,
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksByTitleAsync(string title, string userName, string guid) {
            this.GetAllBooksByTitleAsync(title, userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksByTitleAsync(string title, string userName, string guid, object userState) {
            if ((this.GetAllBooksByTitleOperationCompleted == null)) {
                this.GetAllBooksByTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksByTitleOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksByTitle", new object[] {
                        title,
                        userName,
                        guid}, this.GetAllBooksByTitleOperationCompleted, userState);
        }
        
        private void OnGetAllBooksByTitleOperationCompleted(object arg) {
            if ((this.GetAllBooksByTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksByTitleCompleted(this, new GetAllBooksByTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksByUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooksByUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksByUser", new object[] {
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksByUserAsync(string userName, string guid) {
            this.GetAllBooksByUserAsync(userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksByUserAsync(string userName, string guid, object userState) {
            if ((this.GetAllBooksByUserOperationCompleted == null)) {
                this.GetAllBooksByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksByUserOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksByUser", new object[] {
                        userName,
                        guid}, this.GetAllBooksByUserOperationCompleted, userState);
        }
        
        private void OnGetAllBooksByUserOperationCompleted(object arg) {
            if ((this.GetAllBooksByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksByUserCompleted(this, new GetAllBooksByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksByAuthor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooksByAuthor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string authorName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksByAuthor", new object[] {
                        authorName,
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksByAuthorAsync(string authorName, string userName, string guid) {
            this.GetAllBooksByAuthorAsync(authorName, userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksByAuthorAsync(string authorName, string userName, string guid, object userState) {
            if ((this.GetAllBooksByAuthorOperationCompleted == null)) {
                this.GetAllBooksByAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksByAuthorOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksByAuthor", new object[] {
                        authorName,
                        userName,
                        guid}, this.GetAllBooksByAuthorOperationCompleted, userState);
        }
        
        private void OnGetAllBooksByAuthorOperationCompleted(object arg) {
            if ((this.GetAllBooksByAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksByAuthorCompleted(this, new GetAllBooksByAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksByGenre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooksByGenre([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string genre, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksByGenre", new object[] {
                        genre,
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksByGenreAsync(string genre, string userName, string guid) {
            this.GetAllBooksByGenreAsync(genre, userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksByGenreAsync(string genre, string userName, string guid, object userState) {
            if ((this.GetAllBooksByGenreOperationCompleted == null)) {
                this.GetAllBooksByGenreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksByGenreOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksByGenre", new object[] {
                        genre,
                        userName,
                        guid}, this.GetAllBooksByGenreOperationCompleted, userState);
        }
        
        private void OnGetAllBooksByGenreOperationCompleted(object arg) {
            if ((this.GetAllBooksByGenreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksByGenreCompleted(this, new GetAllBooksByGenreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/GetAllBooksByType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResultSetOfBookUcBWdBTS GetAllBooksByType([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string type, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("GetAllBooksByType", new object[] {
                        type,
                        userName,
                        guid});
            return ((OperationResultSetOfBookUcBWdBTS)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllBooksByTypeAsync(string type, string userName, string guid) {
            this.GetAllBooksByTypeAsync(type, userName, guid, null);
        }
        
        /// <remarks/>
        public void GetAllBooksByTypeAsync(string type, string userName, string guid, object userState) {
            if ((this.GetAllBooksByTypeOperationCompleted == null)) {
                this.GetAllBooksByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllBooksByTypeOperationCompleted);
            }
            this.InvokeAsync("GetAllBooksByType", new object[] {
                        type,
                        userName,
                        guid}, this.GetAllBooksByTypeOperationCompleted, userState);
        }
        
        private void OnGetAllBooksByTypeOperationCompleted(object arg) {
            if ((this.GetAllBooksByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllBooksByTypeCompleted(this, new GetAllBooksByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBookManagement/ReserveBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OperationResult ReserveBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Book book, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("ReserveBook", new object[] {
                        book,
                        userName,
                        guid});
            return ((OperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveBookAsync(Book book, string userName, string guid) {
            this.ReserveBookAsync(book, userName, guid, null);
        }
        
        /// <remarks/>
        public void ReserveBookAsync(Book book, string userName, string guid, object userState) {
            if ((this.ReserveBookOperationCompleted == null)) {
                this.ReserveBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveBookOperationCompleted);
            }
            this.InvokeAsync("ReserveBook", new object[] {
                        book,
                        userName,
                        guid}, this.ReserveBookOperationCompleted, userState);
        }
        
        private void OnReserveBookOperationCompleted(object arg) {
            if ((this.ReserveBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveBookCompleted(this, new ReserveBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class Author {
        
        private int authorIdField;
        
        private bool authorIdFieldSpecified;
        
        private string authorInfoField;
        
        private string bornDateField;
        
        private string deathDateField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        public int AuthorId {
            get {
                return this.authorIdField;
            }
            set {
                this.authorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthorIdSpecified {
            get {
                return this.authorIdFieldSpecified;
            }
            set {
                this.authorIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthorInfo {
            get {
                return this.authorInfoField;
            }
            set {
                this.authorInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BornDate {
            get {
                return this.bornDateField;
            }
            set {
                this.bornDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeathDate {
            get {
                return this.deathDateField;
            }
            set {
                this.deathDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Library.Models")]
    public partial class BookOfInterest {
        
        private string authorNameField;
        
        private int bookIdField;
        
        private bool bookIdFieldSpecified;
        
        private string titleField;
        
        private User userField;
        
        private int userIdField;
        
        private bool userIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthorName {
            get {
                return this.authorNameField;
            }
            set {
                this.authorNameField = value;
            }
        }
        
        /// <remarks/>
        public int BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BookIdSpecified {
            get {
                return this.bookIdFieldSpecified;
            }
            set {
                this.bookIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public User User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class User {
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private Location locationField;
        
        private string phoneField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class Location {
        
        private string addressField;
        
        private string cityField;
        
        private string countryField;
        
        private string postCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class Book {
        
        private Author authorField;
        
        private int bookIdField;
        
        private bool bookIdFieldSpecified;
        
        private string genreField;
        
        private string isbnField;
        
        private bool reservedField;
        
        private bool reservedFieldSpecified;
        
        private string titleField;
        
        private string typeField;
        
        private User userField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Author Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public int BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BookIdSpecified {
            get {
                return this.bookIdFieldSpecified;
            }
            set {
                this.bookIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
            }
        }
        
        /// <remarks/>
        public bool Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReservedSpecified {
            get {
                return this.reservedFieldSpecified;
            }
            set {
                this.reservedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public User User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationResultSetOfBookOfInterest6WXd3OUP))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationResultSetOfBookUcBWdBTS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationResultValueOfstring))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationResultSetOfstring))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationResultSetOfAuthorUcBWdBTS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class OperationResult {
        
        private OperationResultErrorEnum errorField;
        
        private bool errorFieldSpecified;
        
        private string errorStringField;
        
        /// <remarks/>
        public OperationResultErrorEnum Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorSpecified {
            get {
                return this.errorFieldSpecified;
            }
            set {
                this.errorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorString {
            get {
                return this.errorStringField;
            }
            set {
                this.errorStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OperationResult.ErrorEnum", Namespace="http://schemas.datacontract.org/2004/07/Library.Models")]
    public enum OperationResultErrorEnum {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        InvalidInputData,
        
        /// <remarks/>
        InternalProblem,
        
        /// <remarks/>
        NotAuthenticated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class OperationResultSetOfBookOfInterest6WXd3OUP : OperationResult {
        
        private BookOfInterest[] resultSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Library.Models")]
        public BookOfInterest[] ResultSet {
            get {
                return this.resultSetField;
            }
            set {
                this.resultSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class OperationResultSetOfBookUcBWdBTS : OperationResult {
        
        private Book[] resultSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Book[] ResultSet {
            get {
                return this.resultSetField;
            }
            set {
                this.resultSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class OperationResultValueOfstring : OperationResult {
        
        private string resultValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResultValue {
            get {
                return this.resultValueField;
            }
            set {
                this.resultValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class OperationResultSetOfstring : OperationResult {
        
        private string[] resultSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ResultSet {
            get {
                return this.resultSetField;
            }
            set {
                this.resultSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Library.Models")]
    public partial class OperationResultSetOfAuthorUcBWdBTS : OperationResult {
        
        private Author[] resultSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Author[] ResultSet {
            get {
                return this.resultSetField;
            }
            set {
                this.resultSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddAuthorCompletedEventHandler(object sender, AddAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllAuthorsCompletedEventHandler(object sender, GetAllAuthorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllAuthorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllAuthorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfAuthorUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfAuthorUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllTypesCompletedEventHandler(object sender, GetAllTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfstring Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfstring)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllGenresCompletedEventHandler(object sender, GetAllGenresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllGenresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllGenresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfstring Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfstring)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddBookCompletedEventHandler(object sender, AddBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultValueOfstring Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultValueOfstring)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EditBookCompletedEventHandler(object sender, EditBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddBookOfInterestCompletedEventHandler(object sender, AddBookOfInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBookOfInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBookOfInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckBookOfInterestCompletedEventHandler(object sender, CheckBookOfInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBookOfInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBookOfInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksOfInterestCompletedEventHandler(object sender, GetAllBooksOfInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksOfInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksOfInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookOfInterest6WXd3OUP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookOfInterest6WXd3OUP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksOfInterestByUserCompletedEventHandler(object sender, GetAllBooksOfInterestByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksOfInterestByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksOfInterestByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookOfInterest6WXd3OUP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookOfInterest6WXd3OUP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksCompletedEventHandler(object sender, GetAllBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksByYearCompletedEventHandler(object sender, GetAllBooksByYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksByYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksByYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksByTitleCompletedEventHandler(object sender, GetAllBooksByTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksByTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksByTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksByUserCompletedEventHandler(object sender, GetAllBooksByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksByAuthorCompletedEventHandler(object sender, GetAllBooksByAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksByAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksByAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksByGenreCompletedEventHandler(object sender, GetAllBooksByGenreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksByGenreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksByGenreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllBooksByTypeCompletedEventHandler(object sender, GetAllBooksByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllBooksByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllBooksByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResultSetOfBookUcBWdBTS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResultSetOfBookUcBWdBTS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReserveBookCompletedEventHandler(object sender, ReserveBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591